export const AUTHENTICATE_USER_FROM_TOKEN = 'AUTHENTICATE_USER_FROM_TOKEN'
export const AUTHENTICATE_USER_FROM_LOGIN = 'AUTHENTICATE_USER_FROM_LOGIN'
export const CREATE_USER_FROM_SIGNUP = 'CREATE_USER_FROM_SIGNUP'
export const TOGGLE_LOADSCREEN = 'TOGGLE_LOADSCREEN'
